{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "doqa.fullname" . }}-backend
  {{- with .Values.serviceMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "doqa.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "doqa.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backend
  endpoints:
  - port: http
    {{- with .Values.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
  {{- with .Values.serviceMonitor.namespace }}
  namespaceSelector:
    matchNames:
    - {{ . }}
  {{- end }}
{{- end }}
